spring.application.name=quantum-mart-services

spring.config.activate.on-profile=dev

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.url=${DB_URL}
spring.flyway.user=${DB_USERNAME}
spring.flyway.password=${DB_PASSWORD}

# Temporary generated value
jwt.secret=1d2i0jf0923thg91wd1uegh03hth13irh9fj31h12rh129

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.root=INFO
# Disables showing database information on startup
logging.level.org.hibernate.orm.connections.pooling=WARN
